---
# vars file for aervits.phoenix
#  phoenix_version: "apache-phoenix-5.0.0-alpha-HBase-2.0"
#  phoenix_url: "http://www-us.apache.org/dist/phoenix/{{ phoenix_version }}/bin/{{ phoenix_version }}-bin.tar.gz"
#  phoenix_sha512_sum: 361f9b671cdddf9326243afa6fa52d7f

